pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t aspnet .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run aspnet'
            }
        }
    }
}