pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t TestApp .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -p 5000:80 --name c_aspnet aspnet'
            }
        }
    }
}